spring:
  jpa:
    
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        show_sql: true
  h2:
    console: 
      enabled: true
  
  datasource:
    url: jdbc:h2:file:./demo-ia-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
      
server:
  servlet:
    context-path: /api/
    
         