spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        show_sql: true
  h2:
    console: 
      enabled: true
  
  datasource:
    url: jdbc:h2:file:./demo-ia-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  redis:
    host: localhost
    port: 6379
  
  kafka:
    client-id: kafka-api-consumer
    consumer:
      group-id: kafka-consumer
      bootstrap-servers:
      - localhost:9092
    
  session:
    store-type: redis
      
server:
  servlet:
    context-path: /api/
    
demo_ia_back:
  realm: demo_ia_back
  rabbitmq:
    queue: demo_ia_back_queue
    exchange: demo_ia_back_exchange
    topic:
      routing_key: email_sent_event
  kafka:
    topic:
      routing_key: email_sent_event_kafka
      routing_key_admin: email_sent_event_kafka_admin
      