spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        show_sql: true
  h2:
    console: 
      enabled: true
  
  datasource:
    url: jdbc:h2:file:./demo-ia-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
      
server:
  servlet:
    context-path: /api/
    
demo_ia_back:
  realm: demo_ia_back
  rabbitmq:
    queue: demo_ia_back_queue
    exchange: demo_ia_back_exchange
    topic:
      routing_key: email_sent_event
